# **AI ASSIGNMENT-01**
# **NAME:K.SAI ROHITH REDDY**

#**REGNO:20MID0084**

#**COLLEGE:VIT VELLORE**

#**EMAIL:sairohith.reddyk2020@vitstudent.ac.in**

#IMPORTING REQUIRED LIBRARIES

In [ ]:
import pandas as pd
import numpy as np

## TASK-01: Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)

In [ ]:
# Setting the random.seed
np.random.seed(51)
# Create random values
data=np.random.rand(4,4)

In [ ]:
print(data)

[[0.67573142 0.04471218 0.34330367 0.64401973]
 [0.284213   0.94933781 0.15767017 0.38797296]
 [0.58999368 0.48779579 0.17434339 0.21818256]
 [0.64674554 0.24983141 0.41024799 0.04772578]]


In [ ]:
#Create the DataFrame
df=pd.DataFrame(data,columns=["Feature_1","Feature_2","Feature_3","Feature_4"])

In [ ]:
print(df)

   Feature_1  Feature_2  Feature_3  Feature_4
0   0.675731   0.044712   0.343304   0.644020
1   0.284213   0.949338   0.157670   0.387973
2   0.589994   0.487796   0.174343   0.218183
3   0.646746   0.249831   0.410248   0.047726


## TASK-02: Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4

In [ ]:
df.rename(columns={'Feature_1': 'Random value 1', 'Feature_2': 'Random value 2',
                   'Feature_3': 'Random value 3', 'Feature_4': 'Random value 4'},
          inplace=True)


In [ ]:
print(df)

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.675731        0.044712        0.343304        0.644020
1        0.284213        0.949338        0.157670        0.387973
2        0.589994        0.487796        0.174343        0.218183
3        0.646746        0.249831        0.410248        0.047726


## TASK-03: Find the descriptive statistics of the 'df' dataframe.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Random value 1  4 non-null      float64
 1   Random value 2  4 non-null      float64
 2   Random value 3  4 non-null      float64
 3   Random value 4  4 non-null      float64
dtypes: float64(4)
memory usage: 256.0 bytes


In [ ]:
# Display descriptive statistics
df.describe(include="all")

Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.549171        0.432919        0.271391        0.324475
std          0.180192        0.388984        0.124904        0.254315
min          0.284213        0.044712        0.157670        0.047726
25%          0.513549        0.198552        0.170175        0.175568
50%          0.618370        0.368814        0.258824        0.303078
75%          0.653992        0.603181        0.360040        0.451985
max          0.675731        0.949338        0.410248        0.644020

## TASK-04: Check for the null values in 'df' and find the data type of the columns

In [ ]:
#finding the missing_Values
null_values=df.isnull().sum()
print(null_values)

Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64


In [ ]:
#checking duplicate_values
df.duplicated().sum()

0

In [ ]:
# Find data types of columns
data_types = df.dtypes
print(data_types)

Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object


## TASK-05: Display the 'Random value 2' & 'Random value 3' columns with location method and index location method

In [ ]:
location_method_columns = df.loc[:, ['Random value 2', 'Random value 3']]
print("Columns using location method:\n", location_method_columns)

Columns using location method:
    Random value 2  Random value 3
0        0.044712        0.343304
1        0.949338        0.157670
2        0.487796        0.174343
3        0.249831        0.410248


In [ ]:
index_location_method_columns=df.iloc[:,1:3]
print("Columns using index location method:\n",index_location_method_columns)

Columns using index location method:
    Random value 2  Random value 3
0        0.044712        0.343304
1        0.949338        0.157670
2        0.487796        0.174343
3        0.249831        0.410248
